### ISSUE TITLE
#3 - ERD 및 아키텍처 설계

### ISSUE THREAD

**Issue by Kyeong6** [jnu-sf-engineering/backend#5]
## ✏️ Description

- 아키텍처 설계

Github actions를 반영한 프로젝트 아키텍처입니다. 
<img width="1026" alt="jnu-sf-engineering-architecture" src="https://github.com/user-attachments/assets/fa89fcb4-7a1a-453d-854e-ba0e9a6f4d1b">

- ERD 설계
![jnu-sf-engineering-erd](https://github.com/user-attachments/assets/b05af550-344e-4c9b-a413-767fc99ffa5e)
기존 ERD에서 USER ~ CARD는 동일하지만, 회고 관련 테이블을 수정했습니다. 그리고 ANSWER 테이블 같은 경우 항목1 ~ 4입니다. 
왜냐하면 CSS, KPT 같은 경우 질문 항목이 3개이지만, 4Ls은 항목이 4개이므로 항목4 attribute까지 추가했습니다. 
이럴 경우 원래는 MongoDB 같은 NoSQL을 사용해야하는데 저희가 NoSQL까지 사용하기에는 여러 측면에서 힘들 것 같아서 RDB를 사용하는 대신 KPT, CSS의 answer_id에 따른 항목4의 NULL 값 처리 로직을 잘 수행해야할 것 같습니다. 
@Yeonsu-Sim , @jisong017 

## Etc.

@Klomachenko 확인 부탁드립니다!

**Comment by Yeonsu-Sim** [comment]
Template과 Answer를 구분해서 테이블을 따로 만드는 것 보다는,
RETROSPECT 테이블을 부모로 하는 KPT, CSS, 4LS 테이블을 따로 만들어서 상속관계로 형성하는 것은 어떨까요?

이렇게 하면 테이블마다 해당하는 항목명으로 에트리뷰트를 작성할 수 있어서 가시성이 좋고,
항목에대한 NULL값도 따로 처리할 필요가 없어요!

상속관계 매핑 전략으로는 JOINED가 적절해 보입니당
그 이유는 각 항목들에 대한 답변이 적어도 50자는 넘을 거라서, 
메모리 공간을 좀 더 효율적으로 사용하는 편이 좋겠다고 판단했어요!

<img width="563" alt="image" src="https://github.com/user-attachments/assets/06c46ef5-1ad7-4aa0-8ab2-de67c15ec71d">

[참고할만한 블로그](https://codingcho.tistory.com/156)
참고할만한 서적: 김영한님의 자바 ORM 표준 JPA 프로그래밍 7장. 고급매핑

**Comment by Kyeong6** [comment]
저는 하나의 테이블에 여러 유형의 데이터를 통합해서 저장하는 방식을 사용했는데, 데이터 구조 차이로 인한 NULL 값이 존재하니까 상속 관계를 활용해 RETROSPECT 테이블을 부모로 두고 각 템플릿(KPT, CSS, 4LS)을 자식 테이블로 분리하는 방식이 더 적합할 것 같습니다! 
반영하도록 하겠습니다 ~

**Comment by Kyeong6** [comment]
![소공론 (1)](https://github.com/user-attachments/assets/4938163c-36e3-40c0-8365-a3b97183873f)
ERD 수정본입니다.

**Comment by Yeonsu-Sim** [comment]
CARD 테이블의 담당자를 참여자로 바꾸면 좋을거 같아요!!
- `card_manager` -> `card_participants`
